version: '3.8'

services:
  nginx_tracker:
    image: nginx:latest
    ports:
      - 12345:80
    depends_on:
      - php_tracker
    volumes:
      - ./app:/srv/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  database_tracker:
    image: postgres:15-alpine3.17
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tracker_user
      - POSTGRES_DB=tracker_db
      - POSTGRES_PASSWORD=tracker_password
    ports:
      - 5432:5432

  php_tracker:
    build: docker/php
    depends_on:
      - database_tracker
    volumes:
      - ./app:/srv/www

volumes:
  postgresql_data:
