controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_register:
    path: /register
    controller: App\Controller\UserController::register

app_login:
    path: /login
    controller: App\Controller\UserController::login

app_logout:
    path: /logout
    controller: App\Controller\UserController::logout

category_add:
    path: /category
    controller: App\Controller\CategoryController::add
    methods: POST

category_list:
    path: /categories
    controller: App\Controller\CategoryController::list
    methods: GET

expense_add:
    path: /expense
    controller: App\Controller\ExpenseController::add
    methods: POST

income_add:
    path: /income
    controller: App\Controller\IncomeController::income
    methods: POST

expense_list:
    path: /expenses
    controller: App\Controller\ExpenseController::list
    methods: GET
