### GET request with parameter
GET http://localhost:12345/api/expenses?start=0&size=10
Accept: application/json

### Send POST request with json body
POST http://localhost:12345/api/expense
Content-Type: application/json


{
  "description": "2description",
  "amount": 1.1,
  "categoryId": 4
}


### Send POST request with json body
GET http://localhost:12345/api/expenses/filter
Content-Type: application/json

{
  "category_id": 1,
  "amount_greater": 10,
  "amount_less": 100000,
  "start_date": "2023-07-01",
  "end_date": "2023-08-01"
}


### Send POST request with json body
GET http://localhost:12345/api/expenses/aggregate
Content-Type: application/json

{
  "category_id": 1,
  "amount_greater": 1000,
  "amount_less": 10000,
  "start_date": "2023-07-27",
  "end_date": "2023-09-01"
}
