### GET request with parameter
GET http://localhost:12345/api/incomes?start=0&size=10
Accept: application/json


### Send POST request with json body
POST http://localhost:12345/api/income
Content-Type: application/json

{
  "amount": 11.1,
  "description": "found it"
}


### Send GET request with json body
GET http://localhost:12345/api/income/filter
Content-Type: application/json

{
  "amount_greater": 1000,
  "amount_less": 10000,
  "start_date": "2023-07-27",
  "end_date": "2023-09-01"
}

### Send POST request with json body
GET http://localhost:12345/api/income/aggregate
Content-Type: application/json

{
  "amount_greater": 1000,
  "amount_less": 10000,
  "start_date": "2023-07-27",
  "end_date": "2023-09-01"
}
